#!/bin/bash

export LD_LIBRARY_PATH="$(pwd)/geosupport/version-17d_17.4/lib/"
export GEOFILES="$(pwd)/geosupport/version-17d_17.4/fls/"
export LIBGEO_PATH="$(pwd)/geosupport/version-17d_17.4/lib/libgeo.so"

